{
 "title": "Flink Dashboards for Applications",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "deploymentId",
    "label": "Deployment ID",
    "query": {
     "query": "label_values({__name__=~\"flink_(job|task)manager_Status_JVM_CPU_Load\"},deploymentId)"
    }
   },
   {
    "name": "deploymentName",
    "label": "Deployment Name",
    "query": {
     "query": "label_values({__name__=~\"flink_(job|task)manager_Status_JVM_CPU_Load\",deploymentId=~\"$deploymentId\"}, deploymentName)"
    }
   },
   {
    "name": "task",
    "label": "Task",
    "query": {
     "query": "label_values({__name__=\"flink_taskmanager_job_task_numRecordsOutPerSecond\",deploymentId=\"$deploymentId\"}, task_name)"
    }
   },
   {
    "name": "rocksdb_state",
    "label": "RocksDB State Name",
    "query": {
     "query": "label_values({__name__=~\"flink_taskmanager_job_task_operator_.*_rocksdb_.*\",deploymentId=\"$deploymentId\"}, __name__)"
    }
   },
   {
    "name": "tm_id",
    "label": "TM",
    "query": {
     "query": "label_values({__name__=\"flink_taskmanager_job_task_numRecordsOutPerSecond\",deploymentId=\"$deploymentId\", component=\"taskmanager\"}, tm_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Uptime",
   "type": "stat",
   "description": "The time that the job has been running without interruption.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{deploymentId=\"$deploymentId\"}",
     "legendFormat": "Job {{job_id}}",
     "measurement": "jobmanager_job_uptime"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "description": "Information in restarts:\n\n* `Restarting Time`: The accumulated time it took to restart the job per interval (shown on left y-axis).\n* `#Restarts`: The number of full restarts per interval (shown on right y-axis).\n\n*Note:* If there are multiple jobs for this deployment, each job is shown separately. Alternatively, the first two (disabled) queries show aggregated results over all deployments.",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(\n  increase(flink_jobmanager_job_restartingTime{deploymentId=\"$deploymentId\"}[$__rate_interval]),\n  \"job_id_short\", \"$1...$2\", \"job_id\", \"(\\\\w{6}).*(\\\\w{6})\"\n)\n",
     "legendFormat": "Restarting Time({{job_id_short}})"
    },
    {
     "alias": "Restarting Time",
     "expr": "label_replace(\n  increase(flink_jobmanager_job_numRestarts{deploymentId=\"$deploymentId\"}[$__rate_interval]),\n  \"job_id_short\", \"$1...$2\", \"job_id\", \"(\\\\w{6}).*(\\\\w{6})\"\n)",
     "legendFormat": "#Restarts({{job_id_short}})"
    }
   ]
  },
  {
   "title": "Failed Checkpoints",
   "type": "stat",
   "description": "Failed Checkpoints within the chosen time range.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(flink_jobmanager_job_numberOfFailedCheckpoints{deploymentId=\"$deploymentId\"}[$__range]))",
     "legendFormat": "Job {{job_id}}"
    }
   ]
  },
  {
   "title": "Completed / Pending / Failed Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(flink_jobmanager_job_numberOfCompletedCheckpoints{deploymentId=\"$deploymentId\"}[$__rate_interval])",
     "legendFormat": "Completed"
    },
    {
     "expr": "increase(flink_jobmanager_job_numberOfInProgressCheckpoints{deploymentId=\"$deploymentId\"}[$__rate_interval])",
     "legendFormat": "Pending"
    },
    {
     "expr": "increase(flink_jobmanager_job_numberOfFailedCheckpoints{deploymentId=\"$deploymentId\"}[$__rate_interval])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Completed Checkpoints",
   "type": "stat",
   "description": "Completed Checkpoints within the chosen time range.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(flink_jobmanager_job_numberOfCompletedCheckpoints{deploymentId=\"$deploymentId\"}[$__range]))",
     "legendFormat": "Job {{job_id}}",
     "measurement": "jobmanager_job_numberOfCompletedCheckpoints"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Event Time Lag - 99% Quantile",
   "type": "bargauge",
   "description": "Shows the 99th percentile of the custom histogram metric `eventTimeLag`.\n\nThe shown value is actually the maximum of all operators' subtasks' 99th percentile over all their reported 99th percentile values in the time range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(quantile_over_time(0.99, flink_taskmanager_job_task_operator_eventTimeLag{deploymentId=\"$deploymentId\", quantile=\"0.99\"}[$__range]))",
     "legendFormat": "max(all subtasks)"
    }
   ]
  },
  {
   "title": "Event Time Lag per Operator - 99% Quantile",
   "type": "timeseries",
   "description": "Shows for each operator the max of its subtasks' 99th percentile of the custom histogram metric `eventTimeLag`.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_subtask_index",
     "expr": "max(flink_taskmanager_job_task_operator_eventTimeLag{deploymentId=\"$deploymentId\", quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": "{{operator_name}}",
     "measurement": "taskmanager_job_task_operator_eventTimeLag"
    }
   ]
  },
  {
   "title": "Event Time Lag per Subtask ($task) - 99% Quantile",
   "type": "timeseries",
   "description": "Shows for each subtask of the selected Task `$task` the 99th percentile of the custom histogram metric `eventTimeLag`.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_subtask_index",
     "expr": "max(flink_taskmanager_job_task_operator_eventTimeLag{deploymentId=\"$deploymentId\", quantile=\"0.99\", task_name=\"$task\"}) by (subtask_index)",
     "legendFormat": "{{subtask_index}}",
     "measurement": "taskmanager_job_task_operator_eventTimeLag"
    }
   ]
  },
  {
   "title": "Output Watermark per Subtask ($task)",
   "type": "table",
   "description": "Shows the latest reported output watermarks for each subtask of the selected Task `$task`. Since each subtask reports the watermark independently, you will see different processing time timestamps for each reported watermark. The order of appearances is arbitrary.\n\n* `Invalid date` is likely caused by the watermark being `-infinity`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_subtask_index",
     "expr": "flink_taskmanager_job_task_operator_currentOutputWatermark{deploymentId=\"$deploymentId\", task_name=\"$task\"}"
    }
   ]
  },
  {
   "title": "Processing Time - Event Time ($task)",
   "type": "timeseries",
   "description": "Shows the difference between the current processing time and the event time of all the subtasks of the selected Task `$task`.\n\n*Note:* the processing time only has second-accuracy!",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(timestamp(flink_taskmanager_job_task_operator_currentOutputWatermark{deploymentId=\"$deploymentId\", task_name=\"$task\"})*1000) by (subtask_index) -\nmax(flink_taskmanager_job_task_operator_currentOutputWatermark{deploymentId=\"$deploymentId\", task_name=\"$task\"}) by (subtask_index)",
     "legendFormat": "{{subtask_index}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Source Throughput",
   "type": "bargauge",
   "description": "Sum of all source subtasks' average output records per second in the time range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(flink_taskmanager_job_task_numRecordsOutPerSecond{deploymentId=\"$deploymentId\", task_name=~\".*Source.*\"}[$__range]))",
     "limit": "1"
    }
   ]
  },
  {
   "title": "Records Out/Second per Task",
   "type": "timeseries",
   "description": "For each task, sum of all its subtasks' output records per second.\n\nNote that a sink does not expose this metric and is not shown.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_task_name",
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{deploymentId=\"$deploymentId\", task_name!~\".*Sink.*\"}) by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Records Out/Second per Subtask ($task)",
   "type": "timeseries",
   "description": "Detailed overview of the output records per second of all the subtasks of the selected Task `$task`.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_subtask_index",
     "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{deploymentId=\"$deploymentId\", task_name=\"$task\"}) by (deploymentId,subtask_index)",
     "legendFormat": "{{subtask_index}}",
     "measurement": "taskmanager_job_task_numRecordsOutPerSecond"
    }
   ]
  },
  {
   "title": "Checkpointing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Checkpoint Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Checkpoint Duration",
     "expr": "sum(flink_jobmanager_job_lastCheckpointDuration{deploymentId=\"$deploymentId\"}) by (deploymentId)",
     "legendFormat": "Checkpoint Duration"
    }
   ]
  },
  {
   "title": "Checkpoint Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Checkpoint Size",
     "expr": "sum(flink_jobmanager_job_lastCheckpointSize{deploymentId=\"$deploymentId\"}) by (deploymentId)",
     "legendFormat": "Checkpoint Size"
    }
   ]
  },
  {
   "title": "Checkpoint Alignment Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "min(flink_taskmanager_job_task_checkpointAlignmentTime{deploymentId=\"$deploymentId\"} > 0)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_checkpointAlignmentTime{deploymentId=\"$deploymentId\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(flink_taskmanager_job_task_checkpointAlignmentTime{deploymentId=\"$deploymentId\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Live Data",
   "type": "timeseries",
   "description": "Estimate of the amount of live data in bytes (usually smaller than `.sst` files size due to space amplification).\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_estimate_live_data_size\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Background Errors",
   "type": "timeseries",
   "description": "Monitor the number of background errors in RocksDB.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_background_errors\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Delayed Write Rate",
   "type": "timeseries",
   "description": "Monitor the current actual delayed write rate. 0 means no delay.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_actual_delayed_write_rate\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Pending Compaction Bytes",
   "type": "timeseries",
   "description": "Estimated total number of bytes compaction needs to rewrite to get all levels down to under target size. Not valid for other compactions than level-based.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_estimate_pending_compaction_bytes\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Running Compactions",
   "type": "timeseries",
   "description": "Monitor the number of currently running compactions.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_num_running_compactions\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Pending Compactions",
   "type": "timeseries",
   "description": "Track pending compactions in RocksDB. Returns `1` if a compaction is pending, `0` otherwise.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_compaction_pending\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Write Stopped",
   "type": "timeseries",
   "description": "Track whether write has been stopped in RocksDB. Returns `1` if write has been stopped, `0` otherwise.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_is_write_stopped\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Running Flushes",
   "type": "timeseries",
   "description": "Monitor the number of currently running flushes.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_num_running_flushes\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Pending Flushes",
   "type": "timeseries",
   "description": "Monitor the number of pending memtable flushes in RocksDB.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_mem_table_flush_pending\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Block Cache Usage",
   "type": "timeseries",
   "description": "Monitor the memory size for the entries residing in block cache.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_block_cache_usage\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): MemTable Size",
   "type": "timeseries",
   "description": "Monitor the approximate size of the active, unflushed immutable, and pinned immutable memtables in bytes.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_size_all_mem_tables\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Live Versions",
   "type": "timeseries",
   "description": "Monitor number of live versions. Version is an internal data structure. See RocksDB file `version_set.h` for details. More live versions often mean more `.sst` files are held from being deleted by iterators or unfinished compactions.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_num_live_versions\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Block Cache Pinned Usage",
   "type": "timeseries",
   "description": "Monitor the memory size for the entries being pinned in block cache.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_block_cache_pinned_usage\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Readers Memory Used",
   "type": "timeseries",
   "description": "Estimate the memory used for reading SST tables, excluding memory used in block cache (e.g., filter and index blocks) in bytes.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_estimate_table_readers_mem\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Unreleased Snapshots",
   "type": "timeseries",
   "description": "Monitor the number of unreleased snapshots of the database.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_num_snapshots\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Num Entries (active memtable)",
   "type": "timeseries",
   "description": "Monitor the total number of entries in the active memtable.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_num_entries_active_mem_table\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Num Deletes (active memtable)",
   "type": "timeseries",
   "description": "Monitor the total number of delete entries in the active memtable.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_num_deletes_active_mem_table\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Num Entries (immutable memtables)",
   "type": "timeseries",
   "description": "Monitor the total number of entries in the unflushed immutable memtables.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_num_entries_imm_mem_tables\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "RocksDB($rocksdb_state): Num Deletes (immutable memtables)",
   "type": "timeseries",
   "description": "Monitor the total number of delete entries in the unflushed immutable memtables.\n\nThe values shown here are the sum of all matching operators' state metrics per Task Manager.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"flink_taskmanager_job_task_operator_${rocksdb_state}_rocksdb_num_deletes_imm_mem_tables\",deploymentId=\"$deploymentId\"}) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "TM Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Manager CPU Used (all TMs)",
   "type": "timeseries",
   "description": "The CPU use of each of the TaskManagers:\n* Container CPU in % of total assigned CPU shares",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  0*max({__name__=\"flink_taskmanager_Status_JVM_CPU_Load\",deploymentId=\"$deploymentId\"}) by (pod,tm_id)\n  +\n  on(pod)\n  group_left()\n  (\n    rate(container_cpu_usage_seconds_total{pod=~\"job-.*-taskmanager-.*\",container=~\"flink-taskmanager\"}[5m]) * 1024 * 100\n    /\n    on(pod,id)\n    container_spec_cpu_shares{pod=~\"job-.*-taskmanager-.*\",container=~\"flink-taskmanager\"}\n  )\n) by (deploymentId,tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "Task Manager Memory Used (all TMs)",
   "type": "timeseries",
   "description": "Shows, per TM, the ratio of memory used vs. the configured limit (`container_memory_working_set_bytes / container_spec_memory_limit_bytes`).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  0*max({__name__=\"flink_taskmanager_Status_JVM_Memory_Heap_Committed\",deploymentId=\"$deploymentId\"}) by (pod,tm_id)\n  +\n  on(pod)\n  group_left()\n  sum (container_memory_working_set_bytes{name=\"\"}) by (pod)\n) by (tm_id)\n/\nsum(\n  0*max({__name__=\"flink_taskmanager_Status_JVM_Memory_Heap_Committed\",deploymentId=\"$deploymentId\"}) by (pod,tm_id)\n  +\n  on(pod)\n  group_left()\n  sum (container_spec_memory_limit_bytes{name=\"\"}) by (pod)\n) by (tm_id)",
     "legendFormat": "{{tm_id}}"
    }
   ]
  },
  {
   "title": "TM Memory Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Manager Memory Details @ $tm_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Direct Used",
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}) by (tm_id)",
     "legendFormat": "Direct Used@{{tm_id}}"
    },
    {
     "alias": "Non-Heap Used",
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_NonHeap_Committed{deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}) by (tm_id)",
     "legendFormat": "Non-Heap Used@{{tm_id}}"
    },
    {
     "alias": "Heap Used",
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Used{deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}) by (tm_id)",
     "legendFormat": "Heap Used@{{tm_id}}"
    },
    {
     "alias": "Heap Committed",
     "expr": "sum(flink_taskmanager_Status_JVM_Memory_Heap_Committed{deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}) by (tm_id)",
     "legendFormat": "Heap Committed@{{tm_id}}"
    },
    {
     "expr": "sum(\n  0*max({__name__=\"flink_taskmanager_Status_JVM_Memory_Heap_Committed\",deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}) by (pod,tm_id)\n  +\n  on(pod)\n  group_left()\n  sum (container_memory_working_set_bytes{name=\"\"}) by (pod)\n) by (tm_id)",
     "legendFormat": "Container working memory set@{{tm_id}}"
    },
    {
     "expr": "sum(\n  0*max({__name__=\"flink_taskmanager_Status_JVM_Memory_Heap_Committed\",deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}) by (pod,tm_id)\n  +\n  on(pod)\n  group_left()\n  sum (container_spec_memory_limit_bytes{name=\"\"}) by (pod)\n) by (tm_id)",
     "legendFormat": "Container limit@{{tm_id}}"
    }
   ]
  },
  {
   "title": "Task Manager GC @ $tm_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "MarkSweepCompact",
     "expr": "idelta(flink_taskmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time{deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}[5m])",
     "legendFormat": "MarkSweepCompact@{{tm_id}}"
    },
    {
     "alias": "Copy",
     "expr": "idelta(flink_taskmanager_Status_JVM_GarbageCollector_Copy_Time{deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}[5m])",
     "legendFormat": "Copy@{{tm_id}}"
    },
    {
     "alias": "Copy",
     "expr": "idelta(flink_taskmanager_Status_JVM_GarbageCollector_PS_Scavenge_Time{deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}[5m])",
     "legendFormat": "PS_Scavenge@{{tm_id}}"
    },
    {
     "alias": "Copy",
     "expr": "idelta(flink_taskmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Time{deploymentId=\"$deploymentId\",tm_id=~\"$tm_id\"}[5m])",
     "legendFormat": "PS_MarkSweep@{{tm_id}}"
    }
   ]
  },
  {
   "title": "JM Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JobManager CPU Used",
   "type": "timeseries",
   "description": "The CPU use of the JobManager:\n* Container CPU in % of total assigned CPU shares\n* JVM Load (disabled by default): 1.0 = 1 CPU core",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  0*max({__name__=\"flink_jobmanager_Status_JVM_CPU_Load\",deploymentId=\"$deploymentId\"}) by (pod)\n  +\n  on(pod)\n  group_right()\n  (\n    rate(container_cpu_usage_seconds_total{pod=~\"job-.*-jobmanager-.*\",container=~\"flink-jobmanager\"}[5m]) * 1024 * 100\n    /\n    on(pod,id)\n    container_spec_cpu_shares{pod=~\"job-.*-jobmanager-.*\",container=~\"flink-jobmanager\"}\n  )\n) by (deploymentId)",
     "legendFormat": "Container CPU usage"
    }
   ]
  },
  {
   "title": "Job Manager Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Direct Used",
     "expr": "sum(flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed{deploymentId=\"$deploymentId\"}) by (deploymentId)",
     "legendFormat": "Direct Used"
    },
    {
     "alias": "Non-Heap Used",
     "expr": "sum(flink_jobmanager_Status_JVM_Memory_NonHeap_Committed{deploymentId=\"$deploymentId\"}) by (deploymentId)",
     "legendFormat": "Non-Heap Used"
    },
    {
     "alias": "Heap Used",
     "expr": "sum(flink_jobmanager_Status_JVM_Memory_Heap_Used{deploymentId=\"$deploymentId\"}) by (deploymentId)",
     "legendFormat": "Heap Used"
    },
    {
     "alias": "Heap Committed",
     "expr": "sum(flink_jobmanager_Status_JVM_Memory_Heap_Committed{deploymentId=\"$deploymentId\"}) by (deploymentId)",
     "legendFormat": "Heap Committed"
    },
    {
     "expr": "sum(\n  0*max({__name__=\"flink_jobmanager_Status_JVM_Memory_Heap_Committed\",deploymentId=\"$deploymentId\"}) by (pod)\n  +\n  on(pod)\n  group_right()\n  sum (container_memory_working_set_bytes{name=\"\"}) by (pod)\n) by (deploymentId)",
     "legendFormat": "Container working memory set"
    },
    {
     "expr": "sum(\n  0*max({__name__=\"flink_jobmanager_Status_JVM_Memory_Heap_Committed\",deploymentId=\"$deploymentId\"}) by (pod)\n  +\n  on(pod)\n  group_right()\n  sum (container_spec_memory_limit_bytes{name=\"\"}) by (pod)\n) by (deploymentId)",
     "legendFormat": "Container limit"
    }
   ]
  },
  {
   "title": "Job Manager GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "MarkSweepCompact",
     "expr": "idelta(flink_jobmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time{deploymentId=\"$deploymentId\"}[5m])",
     "legendFormat": "MarkSweepCompact"
    },
    {
     "alias": "Copy",
     "expr": "idelta(flink_jobmanager_Status_JVM_GarbageCollector_Copy_Time{deploymentId=\"$deploymentId\"}[5m])",
     "legendFormat": "Copy"
    },
    {
     "alias": "Copy",
     "expr": "idelta(flink_jobmanager_Status_JVM_GarbageCollector_PS_Scavenge_Time{deploymentId=\"$deploymentId\"}[5m])",
     "legendFormat": "PS_Scavenge"
    },
    {
     "alias": "Copy",
     "expr": "idelta(flink_jobmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Time{deploymentId=\"$deploymentId\"}[5m])",
     "legendFormat": "PS_MarkSweep"
    }
   ]
  }
 ]
}